Module InfoVB
  Sub Main()
Console.writeline("This is an emulator for 3.0.9 WoW clients.")
Console.writeline("It doesn't work yet..")
Console.WriteLine("    ____   _      _______            _    _         ______")                   
Console.WriteLine("   |  _ \ (_)    |__   __|          | |  | |       |  ____|")                  
Console.WriteLine("   | |_) | _   __ _ | | _   _  _ __ | |_ | |  ___  | |__    _ __ ___   _   _ ")
Console.WriteLine("   |  _ < | | / _` || || | | || '__|| __|| | / _ \ |  __|  | '_ ` _ \ | | | |")
Console.WriteLine("   | |_) || || (_| || || |_| || |   | |_ | ||  __/ | |____ | | | | | || |_| |")
Console.WriteLine("   |____/ |_| \__, ||_| \__,_||_|    \__||_| \___| |______||_| |_| |_| \__,_|")
Console.WriteLine("               __/ |                                                         ")
Console.WriteLine("              |___/                                                          ")
Console.readline


	End Sub
End Module
